-- Run as ACCOUNTADMIN (or a role with MANAGE GRANTS)
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE EXERCISE_ROLE_MSFORM;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE EXERCISE_ROLE_MSFORM;

CREATE OR REPLACE TASK DATAWAREHOUSE.GOLD.TASK_RUN_BRONZE
  AS
  CALL DATAWAREHOUSE.BRONZE.LOAD_BRONZE();

CREATE OR REPLACE TASK DATAWAREHOUSE.GOLD.TASK_RUN_SILVER
  AFTER DATAWAREHOUSE.GOLD.TASK_RUN_BRONZE
  AS
  CALL DATAWAREHOUSE.SILVER.LOAD_SILVER();

ALTER TASK DATAWAREHOUSE.GOLD.TASK_RUN_SILVER RESUME;
ALTER TASK DATAWAREHOUSE.GOLD.TASK_RUN_BRONZE RESUME;
